var quotes = [
	["Don't cry because it's over, smile because it happened.", "Dr. Seuss"],
	["Be yourself; everyone else is already taken.", "Oscar Wilde"],
	["Two things are infinite: The Universe and human stupidity; and I'm not sure about The Universe.", "Albert Einstein"],
	["You know you're in love when you can't fall asleep because reality is finally better than your dreams.", "Dr. Seuss"],
	["Be the change that you wish to see in the world.", "Mahatma Gandhi"],
	["A friend is someone who knows all about you and still loves you.", "Elbert Hubbard"],
	["Always forgive your enemies; nothing annoys them so much.", "Oscar Wilde"],
	["My batteries are low, and it's getting dark.", "Mars Rover"],
	["Dear Math, please grow up and solve your own problems, I'm tired of solving them for you.", "Anonymous"],
	["I try to contain my craziness, but the lid keeps popping off.", "Anonymous"],
	["I'm not stubborn, my way is just better than yours.", "Anonymous"],
	["Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.", "Albert Einstein"],
	["Teamwork - working together towards a common goal... Until a 'difference of opinion' gets someone dropped into molten lava.", "Anonymous"],
	["When you fall, get back up. Otherwise you're stuck on the ground wondering what you did wrong.", "Anonymous"],
	["There's a snake in my boot.", "Woody Pride"],
	["42.", "Deep Thought"],
	["Life is fun.", "Odd1sOut"],
	["RIP Milo 2019 - 2019.", "Wilbur Soot"],
	["If I won the award for laziness, I would send somebody to pick it up for me.", "Anonymous"],
	["Why do they call it beauty sleep when you wake up looking terrible?", "Anonymous"],
	["Some people aren't just missing a screw, the whole toolbox is gone.", "Anonymous"],
	["Stop worrying about the world ending today. It's already tomorrow in Australia.", "Charles M. Schulz"],
	["A mind is like a parachute. It doesn't work if it is not open.", "Frank Zappa"],
	["A cop pulled me over and told me \"Papers\", so I said \"Scissors, I win!\" and drove off.", "Anonymous"],
	["The difference between stupidity and genius is that genius has its limits.", "Albert Einstein"],
	["If what you've done is stupid but it works, then it really isn't that stupid at all.", "David Letterman"],
	["I told the doctor I broke my leg in two places. He told me to quit going to those places.", "Henny Youngman"],
	["Flying is learning how to throw yourself at the ground and miss.", "Douglas Adams"],
	["A girl asked me once if I was married, I said: \"No, I'm Alone in this life, you?\"", "Anonymous"],
	["What are you delivering? Get outta here; I'm delivering people - the most valuable of all goods.", "Wilbur Soot"],
	["The best way to make your dreams come true is to wake up.", "Paul Valery"],
	["Hello World!", "My first computer program"],
	["Meow.", "Nyan Cat"],
	["Until man duplicates a blade of grass, nature can laugh at his so-called scientific knowledge.", "Thomas Alva Edison"],
	["Very simple ideas lie within the reach only of complex minds.", "Remy de Gourmant"],
	["Blind faith in your leaders, or in anything, will get you killed.", "Bruce Springsteen"],
	["Everybody wants to be Cary Grant. Even I want to be Cary Grant.", "Cary Grant"],
	["Spring is when you feel like whistling even with a shoe full of slush.", "Doug Larson"],
	["To be or not to be?", "Shakespeare"],
	["There's no way I'm giving you a quote to make a stupid quote thing.", "Lucas Lehman"],
	["If a pregnant woman swims, she is a human submarine.", "Anonymous"],
	["I can picture in my mind a world without war, a world without hate. And I can picture us attacking that worldbecause they'd never expect it.", "Anonymous"],
	["For some reason, the crows keep calling my name. I don't know why.", "Caw Jackson"],
	["If the mind is quiet, the soul will speak.", "Anonymous"],
	["Inside every person you know there's a lot of different organs.", "Anonymous"],
	["There is a light at the end of every tunnel, just pray it's not a train.", "Anonymous"]
];
