var allTracks = [
	["automate", "Automate", "Magnogen", "Unspecified", ["old", "style", "alan", "walker", "automate", "unspecified", "planet"]],
	["breeze", "Breeze", "Magnogen", "Unspecified", ["old", "style", "breeze", "unspecified", "planet", "calm"]],
	["vsauce", "Vsauce", "Magnogen", "Unspecified", ["unspecified", "old", "style", "vsauce", "spacey", "space", "youtube", "channel", "hey", "calm"]],
	["renegade", "Renegade", "Magnogen", "Electro", ["planet", "electro", "old", "style", "renegade", "electro", "electronic", "electric", "8bit"]],
	["scars", "Scars [Magnogen remix]", "Zyzyx", "Lofi", ["lofi", "calm", "old", "style", "zyzyx", "remix", "remixes", "scars", "bass"]],
	["laughter", "Laughter", "Magnogen", "Electro", ["emotions", "emotion", "laughter", "laugh", "mario", "game", "electro", "electronic", "electric", "8bit", "upbeat", "fast", "happy"]],
	["adrenaline", "Adrenaline", "Magnogen", "Hardcore", ["hardcore", "hard", "adrenaline", "fast", "singles", "electro", "bass"]],
	["impurity", "Impurity", "Magnogen", "DnB/Hardcore/Future Bass", ["genres", "genre", "flavour", "full", "drum", "bass", "future", "dnb", "hard", "hardcore"]],
	["insane", "Insane", "Magnogen", "Drumstep", ["insane", "drum", "step", "dub", "dubstep", ""]],
	["radius", "Radius", "Magnogen", "Chillstep", ["radius", "chillstep", "chill", "dub", "step", "dubstep", "relaxed", "calm"]],
	["heartbeat", "Heartbeat", "Magnogen", "Trance", ["heartbeat", "trance", "chill", "psytrance", "psy", "heart", "beat", "electronic", "electro"]],
	["dejavu", "Déjà Vu", "Magnogen", "Trap", ["deja", "déjà", "vu", "trap", "dejavu", "bass", "heavy"]],
	["avocado", "Avocado", "Magnogen", "Deathstep", ["death", "dub", "step", "dubstep", "deathstep", "avocado", "choir", "ahh", "spooky"]],
	["pixelate", "Pixelate", "Magnogen", "Electro", ["squres", "pixel", "pixels", "pixelate", "electro", "electronic", "electric", "8bit"]]
]
var ids = [
	"automate",
	"breeze",
	"vsauce",
	"renegade",
	"scars",
	"laughter",
	"adrenaline",
	"impurity",
	"insane",
	"radius",
	"heartbeat",
	"dejavu",
	"avocado",
	"pixelate",
]
var soundcloudLinks = [
	"634433973",
	"634456503",
	"634457475",
	"634458069",
	"634458684",
	"634459437",
	"634461603",
	"634462842",
	"634463517",
	"634464411",
	"643406646",
	"634465800",
	"643405845",
	"643407042",
]
